FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
ADD . /bioapp
COPY bio.py /bioapp
COPY templates /bioapp/templates
WORKDIR /bioapp
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["bio.py"]