FROM python:3.6-alpine

ENV DEVELOPER="Alejandra Lemus"
ADD . /bioapp
COPY bio.py /bioapp
COPY templates /bioapp/templates
WORKDIR /bioapp
RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["python", "bio.py"]